<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <!--   <meta content="IE=edge" http-equiv="X-UA-Compatible"> -->
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="" name="description">
    <meta content="" name="author">
    <link href="{{ asset('favicon.ico') }}" rel="shortcut icon">

    <title>{{ config('app.name_cn', 'Laravel') }}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{{ asset('vendor/entrance/css/bootstrap.css') }}">

    <!-- Custom styles for this template -->
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{{ asset('vendor/entrance/css/theme.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/entrance/css/dashboard.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/entrance/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/entrance/css/dripicon.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/entrance/css/typicons.css') }}" />
    <link rel="stylesheet" href="{{ asset('vendor/entrance/css/font-awesome.css') }}" />
    <link rel="stylesheet" href="{{ asset('vendor/entrance/css/responsive.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/entrance/js/tip/tooltipster.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('vendor/entrance/js/vegas/jquery.vegas.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('vendor/entrance/js/number-progress-bar/number-pb.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/entrance/js/layer/skin/default/layer.css') }}">
    <!-- pace loader -->
    <script src="{{ asset('vendor/entrance/js/pace/pace.js') }}"></script>
    <link href="{{ asset('vendor/entrance/js/pace/themes/orange/pace-theme-flash.css') }}" rel="stylesheet" />



    {{--<link rel="stylesheet" href="css/theme.css">
    <link rel="stylesheet" href="css/dashboard.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/dripicon.css">
    <link rel="stylesheet" href="css/typicons.css" />
    <link rel="stylesheet" href="css/font-awesome.css" />
    <link rel="stylesheet" href="css/responsive.css">
    <link rel="stylesheet" href="js/tip/tooltipster.css">
    <link rel="stylesheet" type="text/css" href="js/vegas/jquery.vegas.css" />
    <link rel="stylesheet" type="text/css" href="js/number-progress-bar/number-pb.css">
    <!-- pace loader -->
    <script src="js/pace/pace.js"></script>
    <link href="js/pace/themes/orange/pace-theme-flash.css" rel="stylesheet" />--}}
</head>

<body>

<div id="preloader">
    <div id="status">&nbsp;</div>
</div>

<div class="container-fluid ">
    <div class="row">
        <div class="col-lg-12">
            <a class="navbar-brand lockscreen-text text-white" href="#">
                {{--<img src="{{ url('logo_80.png') }}" alt="" class="" style="width: 50px">--}}
                {{ config('app.name_cn', 'Laravel')}}</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">

            <!-- Comtainer -->

            <div class="headline text-center" id="time">
                <!-- Time auto generated by js -->

            </div>
            <!-- /.headline -->



            <!-- START LOCK SCREEN ITEM -->
            <div class="lockscreen-item">
                <!-- lockscreen image -->


                <!-- lockscreen credentials (contains the form) -->
                <div class="lockscreen-credentials">

                    <div class="input-group">
                            <input id="pwu" type="password" name="passwordU" class="form-control" placeholder="password" onkeydown="myKeyDown(event)"/>
                        <div class="input-group-btn">
                            <button onclick="event.preventDefault(); $('#pwd').val($('#pwu').val()); document.getElementById('lock_screen_form').submit();" class="btn btn-flat"><i class="fa fa-arrow-right text-muted"></i>
                            </button>
                        </div>
                        <form id="lock_screen_form" action="{{ url('lockScreen') }}" method="POST" style="display: none;">
                         <input type="hidden" name="password" id="pwd">
                        {{ csrf_field() }}
                        </form>
                    </div>
                </div>
                <!-- /.lockscreen credentials -->
            </div>

            <!-- /.lockscreen-item -->

            <div class="lockscreen-link">
                @if(!empty($errors))
                    <p class="text-white"><strong>{{ $errors->first() }}</strong></p>
                @endif
                <a href="{{ route('login') }}" class="text-white">或者以其他用户身份登录</a>
            </div>

            <!-- /.center -->
            <!-- / FOOTER -->
            <!-- Container -->
        </div>
    </div>
</div>

{{--<div class="slide-out-div">
    <a class="handle" href="http://link-for-non-js-users"></a>
    <ul class="theme-bg">
        <li>
            <div id="button-bg"></div>
        </li>
        <li>
            <div id="button-bg2"></div>
        </li>
        <li>
            <div id="button-bg3"></div>
        </li>
        <li>
            <div id="button-bg4"></div>
        </li>
        <li>
            <div id="button-bg5"></div>
        </li>
        <li>
            <div id="button-bg6"></div>
        </li>

    </ul>
</div>--}}

<!--
================================================== -->
<!-- Main jQuery Plugins -->
<script type='text/javascript' src="{{ asset('vendor/entrance/js/jquery.js') }}"></script>
<script type='text/javascript' src="{{ asset('vendor/entrance/js/vegas/jquery.vegas.js') }}"></script>
<script type='text/javascript' src="{{ asset('vendor/entrance/js/image-background.js') }}"></script>
<script type='text/javascript' src="{{ asset('vendor/entrance/js/jquery.tabSlideOut.v1.3.js') }}"></script>
<script type='text/javascript' src="{{ asset('vendor/entrance/js/bg-changer.js') }}"></script>

{{--<script type='text/javascript' src='js/vegas/jquery.vegas.js'></script>
<script type='text/javascript' src='js/image-background.js'></script>
<script type="text/javascript" src="js/jquery.tabSlideOut.v1.3.js"></script>
<script type="text/javascript" src="js/bg-changer.js"></script>--}}

<script type="text/javascript">
    $(function() {
        startTime();
        $(".center").center();
        $(window).resize(function() {
            $(".center").center();
        });

        //防止页面后退
        history.pushState(null, null, document.URL);
        window.addEventListener('popstate', function () {
            history.pushState(null, null, document.URL);
        });
    });

    /*  */
    function startTime() {
        var today = new Date();
        var h = today.getHours();
        var m = today.getMinutes();
        var s = today.getSeconds();

        // add a zero in front of numbers<10
        m = checkTime(m);
        s = checkTime(s);

        //Check for PM and AM
        var day_or_night = (h > 11) ? "<small>PM</small>" : "<small>AM</small>";

        //Convert to 12 hours system
        if (h > 12)
            h -= 12;

        //Add time to the headline and update every 500 milliseconds
        $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
        setTimeout(function() {
            startTime()
        }, 500);
    }

    function checkTime(i) {
        if (i < 10) {
            i = "0" + i;
        }
        return i;
    }

    /* CENTER ELEMENTS IN THE SCREEN */
    jQuery.fn.center = function() {
        this.css("position", "absolute");
        this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
                $(window).scrollTop()) - 30 + "px");
        this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
                $(window).scrollLeft()) + "px");
        return this;
    }

    function myKeyDown(event){
        var currKey=event.keyCode||event.which||event.charCode;//支持IE、FF
        if (currKey == 13) {
            $('#pwd').val($('#pwu').val());
            document.getElementById('lock_screen_form').submit();
        }
    }
</script>
<script type="text/javascript">
    /*$(function() {
        $("#button-bg").click(function() {
            $("body").css({
                "background": "url('img/wg_blurred_backgrounds_11.jpg')no-repeat center center fixed"
            });
        });

        $("#button-bg2").click(function() {
            $("body").css({
                "background": "url('img/wg_blurred_backgrounds_5.jpg')no-repeat center center fixed"
            });
        });


        $("#button-bg3").click(function() {
            $("body").css({
                "background": "url('img/wg_blurred_backgrounds_9.jpg')no-repeat center center fixed"
            });
        });

        $("#button-bg4").click(function() {
            $("body").css({
                "background": "url('img/wg_blurred_backgrounds_19.jpg')no-repeat center center fixed"
            });
        });


        $("#button-bg5").click(function() {
            $("body").css({
                "background": "url('img/wg_blurred_backgrounds_3.jpg')no-repeat center center fixed"
            });

        });

        $("#button-bg6").click(function() {
            $("body").css({
                "background": "url('img/wg_blurred_backgrounds_6.jpg')no-repeat center center fixed"
            });

        });

        /!**
         * Background Changer end
         *!/
    });*/
</script>




</body>

</html>
